name: 🧪 Run Test Suite 

on:
  push:
    branches: [ tests ]
  pull_request:
    branches: [ tests ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: cd tests/laravel && php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: cd tests/laravel && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: cd tests/laravel && php artisan key:generate
    - name: Directory Permissions
      run: cd tests/laravel && chmod -R 777 storage bootstrap/cache
   
    - name: Start the server
      run:  php tests/laravel/artisan serve
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run:  php tests/laravel/artisan test
